### ISSUE TITLE
Replacement message

### ISSUE THREAD

**Issue by fourroses666** [atillay/cookie-consent-api#15]
First of all thanks allot for this nice cookie script, works very well!

Is it possible to show a custom message when the cookie is not accepted and hidden when is accepted?
I don't see any classes added or removed on an item.

For instance, show a message in a youtube banner, "you need to accept cookies to show the video" which will be hidden when cookies are allowed.

**Comment by cimt** [comment]
I think that...

all in the div "data-cookie-consent" is displayed if not accepted!


`<div data-cookie-consent="youtube">
   **<a href="https://youtube_blank" title="Youtube" target="_blank">you need to accept cookies to show the video ... or play the video on Youtube </a>**
    
</div>`

**Comment by fourroses666** [comment]
Ah your right, within the data-cookie-consent= 

```
<div data-cookie-consent="googleMaps">
        -- all this will be removed :) --
	<!--if-consent
```
