### ISSUE TITLE
Bug on firefox S flag

### ISSUE THREAD

**Issue by elcferreira** [atillay/cookie-consent-api#3]
Hello,
Could this flag `s` be replaced for `g`?
On firefox (76.0.1) is this error happening.

![image](https://user-images.githubusercontent.com/10597659/84051550-a3298680-a9af-11ea-91b2-226bf063fa2e.png)

Firefox reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag

https://github.com/atillay/cookie-consent-api/blob/f961c2d3c6e4ec329cde83a843ff71e91d593e9e/src/index.js#L145

**Comment by atillay** [comment]
It should work now (new release 1.0.4)

**Comment by elcferreira** [comment]
Thank you! It works.
