### ISSUE TITLE
Replace duration to expires

### ISSUE THREAD

**Issue by elcferreira** [atillay/cookie-consent-api#4]
Hello 🙂

The `duration` property doesn’t exist in `js-cookie`library, the right property is `expires`.

https://github.com/js-cookie/js-cookie#basic-usage

https://github.com/atillay/cookie-consent-
api/blob/4c427434e56d255b283bd6c71b92c4cb2139224b/src/index.js#L111

**Comment by atillay** [comment]
Thanks, I should have noticed that ! Fixed v1.05
